# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='bairro',
            field=models.CharField(default=1, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
    ]
