# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_dadospessoais_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='contato',
            field=models.CharField(default='contato', max_length=20, verbose_name='Contato'),
            preserve_default=False,
        ),
    ]
